### ISSUE TITLE
More complete TA EPG

### ISSUE THREAD

**Issue by enduser001** [fHDHR/fHDHR_plugin_origin_ToonamiAftermath#5]
I've been using the EPG from https://github.com/chris102994/docker-toonamiaftermath with this plugin in PLEX.

This allows for a more complete EPG and I hope you may be able to leverage his effort to make your EPG more robust in this plugin.

I like that I can use the direct stream instead of transcoding the TA stream using the xTeve method.

Thank you.

**Comment by deathbybandaid** [comment]
I'll take a look, thanks!
